service: sls-iopipe
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
plugins:
  - serverless-plugin-iopipe/index.js
environment:
  NODE_ENV: ${env:NODE_ENV}
custom:
  iopipeToken: SAMPLE_TOKEN_FOO
  iopipeQuote: double
  iopipeNoVerify: false
  iopipeExclude: excluded,foo
  iopipePlaceholder: false
  extraCustomKey: true
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "logs:*"
    Resource:
      - "*"
functions:
  simple:
    handler: handlers/simple.handler
  multiple:
    handler: handlers/multiple.handler
  es5:
    handler: handlers/es5.handler
  multiple-dots-in-name:
    handler: handlers/multiple.dots.in.name.handler
  noModule:
    handler: handlers/noModule.handler
  excluded:
    handler: handlers/excluded.handler
  es5Named:
    handler: handlers/es5Named.handler
  python:
    handler: python/main.longRunning
    runtime: python2.7
