service: sls-iopipe
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
plugins:
  - serverless-plugin-iopipe/index.js
functions:
  simple:
    handler: handlers/simple.handler
