service: sls-test
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
plugins:
  - serverless-plugin-iopipe/index.js
environment:
  IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "logs:*"
    Resource:
      - "*"
functions:
  simple:
    handler: handlers/simple.handler
